### ISSUE TITLE
trouble with formatting input files correctly

### ISSUE THREAD

**Issue by dmweinhold** [rithinch/pareto-optimal-student-supervisor-allocation#1]
Dear Rithinch,
Thanks so much for this fantastic algorithm. The test files work perfectly, but I keep hitting a 'Key Error' code with my own student and supervisor keyword excel files. They are formatted in exactly the same way as the test files, but my key words are all capitalized. I noticed that I get the same Key Error message and the process aborts when I capitalize the keywords in your student test file as well.  Before I go and reformat all my keywords, however, I was wondering if that was indeed an issue, and if so what other, if any, very strict formatting requirements I should be aware of?  Thanks so much for any help you can provide as I'm very keen to get this up and running to use on the new cohort of incoming students next week.  Best, Diana Weinhold

**Comment by rithinch** [comment]
Hi @dmweinhold,

The reason you're getting a 'Key Error' for both your files and sample test files (capitalized) is that the initial version excepts keywords to be exactly the same as in the [2012 ACM Computing Classification System](https://www.acm.org/publications/class-2012).

To be specific, the application uses [this keywords text file](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/blob/master/pystsup/test/acm.txt). 

At the time of conducting this research, due to time constraints, we opted to conduct experiments only on the Computer Science department; thus ACM keywords. 

If you're planning to use this tool to assist in the allocation of students & supervisors of a Computer Science department, then amending the keywords to match those in ACM text file is the **only** strict requirement to get this tool up and running. :tada:

However, if you're planning to use your own custom keywords, a bit more work needs to be done to the tool to support that. :hourglass_flowing_sand:

A lot can be improved since the initial version of this project from 2 years ago i.e. code, usability and documentation. Eventually, the plan is to make this a generic tool that fits all keywords and isn't restricted to just ACM ones.

Let me know how this goes and if there any issues give me a shout :smile:

Cheers,
Rithin Chalumuri

**Comment by dmweinhold** [comment]
Dear Rithin,
Thanks so much for your fast reply and explanation!  That saves me a lot of detective work, which was going nowhere… (!).  We are indeed trying to use our own set of keywords related to international development.  However it won’t take that much extra work to just create a mapping from our unique keywords to your list (we only have 70) and run the algorithm.   Does your algorithm recognize similarities between key words, in which case we should choose a subset of your words that are as dissimilar as possible so the algorithm treats them as unique and independent.  If it just sees different keywords as unique if they have any difference, however, we can just take the first 70 words off your list.

Thanks again for getting back to me so quickly.  Can you let me know if you get this email (I’m not sure if directly replying will really work…) and let me know what you think of my plan.  I’ll let you know how I get on.

Best
Diana

**Comment by rithinch** [comment]
@dmweinhold,

I've received your email :+1:. 

This comment has markdown elements in it, so it might clearer to view on Github directly.

The algorithm does take into account the similarities between keywords. Explained below is how it computes the similarities between the keywords.

The keywords in the [ACM classification text file](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/blob/master/pystsup/test/acm.txt) aren't just a linear list of words, but instead, they represent a **tree** data structure.

For example, let's consider a simple example similar to that in text file (in a tree view format where level depth is indicated by a **tab**).

```
- Root Node 
	- Keyword 1
		 - Keyword 2 
			 - Keyword 3
			 - Keyword 4
	          - Keyword 5
			 - Keyword 6
```

Suppose we want to find out the similarity between _'Keyword 3'_ and _'Keyword 6'_; we first calculate their **path** in the tree from the root node.

The **path** in the tree from root note to _'Keyword 3'_ is = [**Root node -> Keyword 1 -> Keyword 2 -> Keyword 3**] i.e. total 4 words.

The **path** in the tree from root note to _Keyword 6_ is = [**Root node -> Keyword 1 -> Keyword 5 -> Keyword 6**] i.e. total 4 words.

Now to answer how similar keyword 3 is to keyword 6, we simply **divide** the number of **common words** in both their **paths** by the total number of words in the path for keyword 3.

Notice that we have 2 common words between Keyword 3 and Keyword 6 i.e. 'Root note' and 'Keyword 1, and the total number of words in 'Keyword 3''s path are 4.

So, similarity value between those two words = 2/4 = 0.5. We can say they are 50% similar.

For your scenario, the root node becomes 'International Development'. 

Let me know if it's possible to classify and produce your unique set of keywords in this tree view format text file. 

Tomorrow I'll make a small change to the tool to allow uploading of such custom words and everything should then work as expected.

This gives users the flexibility to structure their unique topics tree and makes it generally applicable to other education departments as well. :sunglasses:

**Comment by dmweinhold** [comment]
Dear Dr. Sanchez-Anguix,

Thank you so much for your fast and thorough reply!  Indeed, after more sleuthing and fiddling I discovered the initial problem was due to the screen resolution so that was easily remedied.  As you note, the larger issue I then discovered, after corresponding with Rithin via GitHub, was that the current algorithm only works with computing topics from the ACM classification.   (By the way, do you have Rithin’s direct email address?  I’m cc’ing him via the GitHub address here to include him in this correspondence, but it may be more efficient to use a more direct address.)

Unfortunately time is not on my side, as the students are arriving next Monday Sept. 23, with their keywords (chosen from a fixed selection of 70 keywords we provided to them, attached here) due by noon on that first day, and we need to assign them supervisors by Tuesday.   It is my fault I’ve boxed myself in like this – when I discovered the algorithm a few months ago and tried it out with the sample files, I was so delighted that I announced problem solved and moved on to other problems (!).  I only just now came back to test it using our own keywords and have realized how much more complex the situation is.

But, I do have a day or two to try to salvage the situation.  Thus, like your colleagues from the Physics department at Liverpool, I am now trying to see whether I can adapt that computer science taxonomy/structure for our case – international development.   I’ve attached our (currently unstructured) list here.  There seems to be two possible ways forward.   I have been corresponding with Rithin via GitHub and he has said he will try to adapt the algorithm to accept alternative taxonomies of keywords, so I will be working this morning to re-arrange the existing list into a structure that emulates the ACM classification.  If it is possible to adapt the algorithm to accept this list, that would be fantastic – but as you note, the programming involved may be more difficult than he envisions.  The back-up plan then would be to map the International Development keyword structure on to the ACM classification as best I can, convert everyone’s International Development keywords into keywords from the ACM classification, and run the original algorithm using the original computer science keywords.  Is this the approach you used with Physics?

Thank you so much again – you have solved an enormous problem, and if the algorithm can be made more general and universally accessible I’m sure you will find a huge demand for it.  In the meantime, I’m not giving up hope yet of using the current  (or a slightly adapted) version for our department this year (!).

Thanks again,

Best Regards,
Diana



From: Victor Sánchez Anguix <vsanchez@florida-uni.es>
Date: Thursday, 19 September 2019 at 07:17
To: "Weinhold,D" <D.Weinhold@lse.ac.uk>, "reyhan.aydogan@ozyegin.edu.tr" <reyhan.aydogan@ozyegin.edu.tr>
Subject: RE: Need help with Student-Supervisor tool please

Dear Diana,

It is nice to meet you. The student-supervisor allocation problem was a project that Rithin (my undergraduate student by that time) and me started as a summer research project. Rithin worked on that project for some months and then his internship finished. I took from there, fixed some issues, and then included some new features into the algorithm. Finally, we published the journal article.

As far as I know, I am the only one that has the latest version (the one published in the journal) and it is placed in a private repository. I was wondering, where did you get the code from? If you did, it is probably an old version.

The GUI does not work properly I believe. It is highly dependent on the screen resolution. By tweaking the screen resolution of the computer, you may be able to fix it. There was a way to fix it in the code too.

In any case, I believe that is not the main issue. Right now, the project only works with computing topics from the ACM classification. I do not know if you talked with my student or if he mentioned that. Extending the project to other disciplines requires some coding and the existence of a taxonomy of topics. I have helped the guys from Physics at Liverpool University to adapt it to their department so it is not impossible. However, it takes some time and I am right now a bit overwhelmed with the start of the course. What disciplines you want to use it with? When will you use it?

Just to let you know, my colleague Reyhan Aydogan and me have started to work on a Web version, easier to use, and usable for several disciplines.

Please, let me know if I can be of any help

Kindest regards,
Dr. Victor Sanchez-Anguix
________________________________
De: Weinhold,D <D.Weinhold@lse.ac.uk>
Enviado: miércoles, 18 de septiembre de 2019 19:40
Para: chalumuriv@uni.coventry.ac.uk <chalumuriv@uni.coventry.ac.uk>; Victor Sánchez Anguix <vsanchez@florida-uni.es>
Asunto: Need help with Student-Supervisor tool please


Dear Dr. Sanchez-Anguiz and Dr. Chalumi,



This is Diana Weinhold, deputy head of department for teaching in the Dept of International Development at LSE.  I am very much hoping to use your brilliant Python based Supervisor-Student Allocation tool to allocate academic mentors for our incoming students this year but have run into a problem which I am finding difficult to understand and I’m very much hoping you will be able to provide some guidance help.



A month or so ago I installed it and ran a few tests and it all worked perfectly.  However, now closer to the arrival date of students I ran another test to make sure everything was ready, and this time there seems to be a problem. Specifically, the User Interface to upload the supervisor and student key words files is missing the ‘browse’ buttons so there is no way to input data files.  I’ve attached a screen shot here.



One thing I did differently this time, which was a mistake, was that before I had re-read the instructions I ran the file “GUI_Application.py” thinking that was the main executable (which it isn’t!), and that may have done something.  Once I realized this was a mistake and remembered the correct way to run the programme – from the desktop shortcut - I uninstalled and reinstalled the programme to try to undo any changes I may have made accidentally.  However that doesn’t seem to have helped – I’ve uninstalled and reinstalled it now several times, including from scratch from the source files on GitHub, but the problem persists.



Can you help?!!



Thanks very much in advance for any help you can provide.



Best Regards,

Diana Weinhold

**Comment by dmweinhold** [comment]
Dear Rithin,
Thanks so much for all your help!  This morning I am working on structuring our keywords in a similar taxonomy to the ACM classification and I will send that to you later this morning (there are only 70 words).

Best,
Diana (d.weinhold@lse.ac.uk)
 
P.S.
Also, as you see above, I've was earlier also in touch with Victor about a much simpler problem that I initially encountered (I had increased the size of icons on my computer and the input no longer worked, but that was easily solved).  Apparently he has helped a physics department to adapt their keywords to work with the existing algorithm, so that may be an alternative back-up plan we could use as a temporary patch for now if it turns out to be too complex to alter the algorithm in time.  At any rate, going forward I'm sure there will be a large demand for this among many departments!

**Comment by dmweinhold** [comment]
Dear Rithin,
Attached please find my list of 70 keywords organised in a branch-tree structure. I have also sent this to Victor, who I believe may be able to map it to the ACM classification (as a backup plan). Let me know if this is enough for what you need, and thanks again so much for all your help. It is GREATLY appreciated!!  
[Structured list of keywords.docx](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/files/3630741/Structured.list.of.keywords.docx)
Best Regards,
Diana

**Comment by rithinch** [comment]
Hi @dmweinhold,

The change has been made and the application is working as expected with the International Development keywords set given. 😄 

Do you have python or anaconda installed i.e. are you able to run the python source code?

**Comment by dmweinhold** [comment]
Hi Rithin,
Wow, thanks!! I'm super excited to try this out!  I do beleive I have python installed, but the proof will come with the pudding.  What do I need to do now? 
Best,
Diana

**Comment by rithinch** [comment]
The following are the steps to get it up and running:

1. You need to get the latest code from this Github Repo - either by clicking download .zip or using git clone.

1. Open **Command Prompt** from Windows Start Menu and navigate to the root location of the folder (repository) where you'll see setup.py. You can use `cd your/path/to/downloaded/folder`

1. Type in the following command to install the dependencies `pip3 install -r ./pystsup/requirements.txt`

1. Then, type in the following command to the install the package `pip3 install .`

1. Final step, to run the application type in the following command `python GUI_Application.py`

I've now added an option to pass in a custom keywords taxonomy text file in the user interface. You will need the upload **international_development_keywords.txt** always for it it to work.

I'm attaching the files here for your reference. 

[international_development_keywords.txt](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/files/3631640/international_development_keywords.txt)
[students_sample_international_development.xlsx](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/files/3631642/students_sample_international_development.xlsx)
[supervisors_sample_international_development.xlsx](https://github.com/rithinch/pareto-optimal-student-supervisor-allocation/files/3631643/supervisors_sample_international_development.xlsx)

Everything from here on should work as it is like you have run in the sample test examples.

Let me know if you have any issues.

**Comment by dmweinhold** [comment]
Dear Rithin,
Thanks very much. I have uninstalled the old Tool and reinstalled using the latest files downloaded from GitHub.  Then I used Command Prompt to navigate to:
C:\Program Files\Student-Supervisor Allocation Tool  which I believe is the root location (?).  From there I entered the pip3 install -r ./pystsup/requirements.txt command, but have got this Error message back: 
Could not open requirements file: [Errno 2] No such file or directory: './pystsup/requirements.txt'

Indeed, within the directory pystsup, I cannot find a file 'requirements.txt', there are only directories for data, evolutionary, test, utilities and a file called 442 _init_.pyc.

I will keep trying ... any hints greatly appreciated!
Best
Diana

**Comment by rithinch** [comment]
@dmweinhold,

We won't be needing the files in 'FinalProduct' folder. Instead, you'll need to download the repository zip file. 

![image](https://user-images.githubusercontent.com/16920458/65255008-0d825a00-daf5-11e9-9129-ae8ed489958d.png)

The root will be where you have placed this downloaded .zip file i.e. after extracting might be in your downloads.

**Comment by dmweinhold** [comment]
Do  you mean where the original zipped folder lands, or where I extract all the files to?  I have now tried again where all the repository files are located (after unzipping them from the original download folder), and from where I ran the *.msi install programme.  Indeed, setup.py is among those files so I thought this was likely the right location. However I'm still getting that same error message as before. Indeed, a search of the whole computer fails to find any file called 'requirements.txt' so perhaps I'm missing something else?
Thanks! 
Best
Diana

**Comment by rithinch** [comment]
@dmweinhold,

Could you post a screenshot of your command prompt?

**Comment by dmweinhold** [comment]
![screen](https://user-images.githubusercontent.com/37543556/65256479-7f5ba300-daf7-11e9-9208-ae8b8b999b99.JPG)

**Comment by rithinch** [comment]
@dmweinhold, yes you're in correct location in command prompt. If you type in the commands mentioned above, it should work.

**Comment by dmweinhold** [comment]
Hmm, same error message.  Also, within the pystsup folder, there is no file called 'requirements.txt' so the error message is correct in that regard... 
![screen2](https://user-images.githubusercontent.com/37543556/65256943-4c65df00-daf8-11e9-90e9-082751823863.JPG)

**Comment by dmweinhold** [comment]
I will try again downloading the repository files from GitHub.  If I understand correctly, I don't have to uninstall and reinstall the programme, though, just extract and overwrite the files in that folder where I am now?

**Comment by rithinch** [comment]
@dmweinhold, is that latest download? because if you navigate to pystsup folder in Github. you can see requirements.txt

**Comment by rithinch** [comment]
> I will try again downloading the repository files from GitHub. If I understand correctly, I don't have to uninstall and reinstall the programme, though, just extract and overwrite the files in that folder where I am now?

Yes , that's correct. Download, extract and overwrite. No need to uninstall or reinstall.

**Comment by dmweinhold** [comment]
Aha, it must not have overwritten then, because in my folder it is not there. I will try downloading again and will check first to make sure it is correct.  Thanks!! Will get back to you shortly to let you know how I get on.

**Comment by dmweinhold** [comment]
Dear Rithin,
It works!!! Yahoo!!  You're a star!  I'm still struggling a bit with my own 'homemade' test files as the programme is very sensitive, but I'll work out the kinks - the test files work perfectly. 

I'm wondering, is it possible to edit the international_development_keywords.txt file?  For example, if I want to add another word or change the branch structure, can I do that directly in that txt file?

In any case THANK YOU!!!! again for all your amazing help!  You have TOTALLY saved the day!!

**Comment by rithinch** [comment]
@dmweinhold,

Glad to hear it works. 😄 

Yes, feel free to edit the keyword tree structure or add how many ever keywords required in the **international_development_keywords.txt** file  (Using Notepad to edit does the job).

The only requirement is that when adding a new branch, it expects a **tab character**. So pressing tab button once on a new line means a new branch i.e. one level deeper than the earlier node in the taxonomy tree. 

You can explore the file further in Notepad to understand the structure a bit more (I've converted the word document you provided to that format as the application expects a tree like structure).

For better results keep the root node it is i.e. '**International Development**'.  Add/Modify as many words as required under the root node.

Please note that the keywords in the text file are case sensitive. So, the words in excel files you upload should exactly match the keywords defined in the tree.

I'll mark this issue as closed. 👍 

If there are any further issues, please feel free to open them on here in Github.

Cheers,
Rithin
